image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

services:
   - docker

test_script:
   - docker run -p 3306:3306 --name=docker-mysql --env="MYSQL_ROOT_PASSWORD=yes" --env="MYSQL_PASSWORD=pass" --env="MYSQL_DATABASE=app" --env=" MYSQL_USER=app" mysql
   - docker run -p 49160:9999 -d gate-simulator
install:
   - java -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/app -jar ./artifacts/aqa-shop.jar &

build_script:
  - ./gradlew test -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации